name: terraform-docs

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  terraform-docs:
    uses: mmccarthy404/reusable-workflows/.github/workflows/terraform-docs.yaml@v2.0.0
    secrets: inherit
    with:
      working-dir: terraform-aws-nat-instance
      output-file: README.md